name: 'Deploy to Azure'
description: 'Deploy resources to azure environment'
inputs:
  environment:
    description: 'Environment to deploy resources to'
    required: true
    default: 'dev'
outputs:
  status: 
    description: "Status"
    value: "Pass"
runs:
  using: "composite"
  steps:
    - run: echo Deploying Azure Resources to following environment ${{ inputs.environment }}
      shell: bash

    - name: Set Environment Variables - ${{ inputs.environment }} # Set Variables based on environment
      uses: deep-mm/set-variables@v1.0
      with:
        variableFileName: 'variable-${{ inputs.environment }}'
        
    - name: Create Resource Group # Create Resource Group using azure cli commands
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --name "${{ env.resourceGroupName }}" --location "eastus"