#Name of the workflow
name: Template-Action-Composite

#Triggers to run the workflow
on:
  workflow_dispatch:

jobs:
  #Release Job
  release-dev:
    uses: deep-mm/TaskgroupGitHubWorkflow/.github/workflows/reusable-template.yml@main
    with:
      env: 'dev'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  release-qa:
    needs: [release-dev]
    uses: deep-mm/TaskgroupGitHubWorkflow/.github/workflows/reusable-template.yml@main
    with:
      env: 'qa'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  release-prd:
    needs: [release-qa]
    uses: deep-mm/TaskgroupGitHubWorkflow/.github/workflows/reusable-template.yml@main
    with:
      env: 'prd'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
